declare namespace _OutlineDefaults {
    let Folder: string;
    let FolderOpen: string;
    let File: string;
    let FileText: string;
    let Spreadsheet: string;
    let Image: string;
    let Code: string;
    let ChevronUp: string;
    let ChevronDown: string;
    let ChevronLeft: string;
    let ChevronRight: string;
    let ArrowUp: string;
    let ArrowDown: string;
    let ArrowLeft: string;
    let ArrowRight: string;
    let Save: string;
    let Close: string;
    let Check: string;
    let Plus: string;
    let Minus: string;
    let Edit: string;
    let Trash: string;
    let Copy: string;
    let Share: string;
    let Search: string;
    let Refresh: string;
    let Download: string;
    let Upload: string;
    let Link: string;
    let ExternalLink: string;
    let Info: string;
    let Warning: string;
    let Error: string;
    let Success: string;
    let Home: string;
    let Settings: string;
    let Menu: string;
    let More: string;
    let Eye: string;
    let EyeOff: string;
    let Lock: string;
    let User: string;
    let Help: string;
}
declare namespace _FilledVariants {
    let Folder_1: string;
    export { Folder_1 as Folder };
    let FolderOpen_1: string;
    export { FolderOpen_1 as FolderOpen };
    let File_1: string;
    export { File_1 as File };
    let FileText_1: string;
    export { FileText_1 as FileText };
    let Spreadsheet_1: string;
    export { Spreadsheet_1 as Spreadsheet };
    let Home_1: string;
    export { Home_1 as Home };
    let Settings_1: string;
    export { Settings_1 as Settings };
    let Trash_1: string;
    export { Trash_1 as Trash };
    let User_1: string;
    export { User_1 as User };
    let Lock_1: string;
    export { Lock_1 as Lock };
    let Info_1: string;
    export { Info_1 as Info };
    let Warning_1: string;
    export { Warning_1 as Warning };
}
export { _OutlineDefaults as Outline, _FilledVariants as Filled };
//# sourceMappingURL=Pict-Icons-Base.d.ts.map